### ISSUE TITLE
Allow materialized views as input table to pivot.

### ISSUE THREAD

**Issue by JohnDeGitt** [jtornero/pivotmytable#4]
Pivotmytable function uses 'information_schema' as source to get details about tables and columns but this schema doesn't contain information about materialized views. One should use Postgresql specific catalog tables (e.g. pg_attribute) which are source of information on all relations (tables, views, materialized views, etc...).
The SQL script can be modified according to Erwin Brandstetter advices as described on http://stackoverflow.com/questions/19127561/how-to-introspect-materialized-views.

**Comment by JohnDeGitt** [comment]
I can push fixes I have made, into new branch but the owner of the project should give me rights to create one.
If this isn't acceptable I can paste e.g. 'git format-patch' output here.

**Comment by jtornero** [comment]
@JohnDeGitt 

Thank you for your interest, and sorry for the long delay for answering you.

You should fork the repository and subsequently make a pull request.

All the best

Jorge
